# Configuration file for feedcrawler.
#
# TOML format
# See https://github.com/toml-lang/toml

# Crawler's setting
[feedcrawler]
# Persistent state file
state_file = "feedcrawler_state.json"

# Number of crawler workers
workers = 3

# Feeds
[feed]
  # [feed.<id>] # id = your favorite unique name for the feed
  # uri                = feed uri
  # title_filter       = regexp pattern for the entry title
  # description_filter = regexp pattern for the entry description
  # content_filter     = regexp pattern for the entry content
  # author_filter      = regexp pattern for the entry author (name and email)
  # category_filter    = regexp pattern for the entry category

  [feed.foo_version]
  uri = "http://localhost:8080/foo.rss"
  title_filter = "release"

  [feed.foo_about]
  uri = "http://localhost:8080/foo.atom"
  title_filter = "(?i:about)"

  [feed.github_all]
  uri = "https://github.com/blog/all.atom"

  [feed.google_api_client_gem]
  uri = "https://rubygems.org/gems/google-api-client/versions.atom"
